---

AWSTemplateFormatVersion: '2010-09-09'

Description: AWS CloudFormation template for infrastructure of django-test Fargate Service

Resources:
  DjangoTestService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: "django-test-service-new"
      TaskDefinition: "django-test-task-definition:6"
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - "sg-001487dcb97cc4099"
          Subnets:
            - "subnet-03feb7e2a5ca70568"
            - "subnet-01f3a0010a174b76f"

      LoadBalancers:
        - TargetGroupArn: "arn:aws:elasticloadbalancing:eu-west-1:514802937958:targetgroup/djang-Defau-QYMIXXGERNZG/02787ea6a8797bc0"
          ContainerPort: 8000
          ContainerName: "django-test"
      Cluster: "django-test-cluster"
